# Generated by Django 3.2.16 on 2022-10-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='squad',
            field=models.CharField(choices=[('lunar', 'Lunar'), ('horizon', 'Horizon'), (' polaris', 'Polaris'), ('voyager', 'Voyager'), ('orion', 'Orion'), ('vanguard', 'Vanguard'), ('practice_group', 'Practice Group')], max_length=128, null=True),
        ),
    ]
