# Generated by Django 3.2.16 on 2022-10-25 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='bookings.office')),
            ],
        ),
    ]
