# Generated by Django 3.2.16 on 2022-10-25 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booked',
            new_name='Booking',
        ),
    ]
